class AppStrings {
  // Language translations
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'app_name': 'Tiffinity',
      'home': 'Home',
      'my_subscriptions': 'My Subscriptions',
      'my_orders': 'My Orders',
      'my_addresses': 'My Addresses',
      'wallet_balance': 'Wallet Balance',
      'favourites': 'Favourites',
      'invite_friends': 'Invite Friends',
      'app_language': 'App Language',
      'help_support': 'Help & Support',
      'faqs': "FAQ's",
      'logout': 'Logout',
      'login': 'Login',
      'profile': 'Profile',
      'contact_details': 'Contact Details',
      'email_address': 'Email Address',
      'phone_number': 'Phone Number',
      'my_account': 'My Account',
      'support_more': 'Support & More',
      'select_language': 'Select Your Preferred Language',
      'language_changed': 'Language changed to',
      'language_info': 'Language changes will be applied to the entire app',
    },
    'hi': {
      'app_name': 'टिफिनिटी',
      'home': 'होम',
      'my_subscriptions': 'मेरी सदस्यता',
      'my_orders': 'मेरे ऑर्डर',
      'my_addresses': 'मेरे पते',
      'wallet_balance': 'वॉलेट बैलेंस',
      'favourites': 'पसंदीदा',
      'invite_friends': 'दोस्तों को आमंत्रित करें',
      'app_language': 'ऐप भाषा',
      'help_support': 'मदद और सहायता',
      'faqs': 'अक्सर पूछे जाने वाले प्रश्न',
      'logout': 'लॉगआउट',
      'login': 'लॉगिन',
      'profile': 'प्रोफाइल',
      'contact_details': 'संपर्क विवरण',
      'email_address': 'ईमेल पता',
      'phone_number': 'फोन नंबर',
      'my_account': 'मेरा खाता',
      'support_more': 'समर्थन और अधिक',
      'select_language': 'अपनी पसंदीदा भाषा चुनें',
      'language_changed': 'भाषा बदली गई',
      'language_info': 'भाषा परिवर्तन पूरे ऐप पर लागू होगा',
    },
    'gu': {
      'app_name': 'ટીફીનિટી',
      'home': 'હોમ',
      'my_subscriptions': 'મારી સબસ્ક્રિપ્શન',
      'my_orders': 'મારા ઓર્ડર્સ',
      'my_addresses': 'મેરાં સરનામાં',
      'wallet_balance': 'વોલેટ બેલેન્સ',
      'favourites': 'મનપસંદ',
      'invite_friends': 'મિત્રોને આમંત્રણ આપો',
      'app_language': 'ઍપ્લિકેશન ભાષા',
      'help_support': 'સહાય અને સમર્થન',
      'faqs': 'વારંવાર પૂછવાતા પ્રશ્નો',
      'logout': 'લૉગઆઉટ',
      'login': 'લૉગીન',
      'profile': 'પ્રોફાઇલ',
      'contact_details': 'સંપર્ક વિગતો',
      'email_address': 'ઈમેલ સરનામું',
      'phone_number': 'ફોન નંબર',
      'my_account': 'મારું ખાતું',
      'support_more': 'સમર્થન અને વધુ',
      'select_language': 'તમારી પસંદીદા ભાષા પસંદ કરો',
      'language_changed': 'ભાષા બદલી',
      'language_info': 'ભાષા પરિવર્તન આખી ઍપ્લિકેશનમાં લાગુ થશે',
    },
    'mr': {
      'app_name': 'टिफिनिटी',
      'home': 'होम',
      'my_subscriptions': 'माझी सदस्यता',
      'my_orders': 'माझे ऑर्डर',
      'my_addresses': 'माझे पते',
      'wallet_balance': 'वॉलेट बॅलेंस',
      'favourites': 'आवडते',
      'invite_friends': 'मित्रांना आमंत्रित करा',
      'app_language': 'ऍप भाषा',
      'help_support': 'मदत आणि समर्थन',
      'faqs': 'वारंवार विचारले जाणारे प्रश्न',
      'logout': 'लॉगआउट',
      'login': 'लॉगिन',
      'profile': 'प्रोफाइल',
      'contact_details': 'संपर्क तपशील',
      'email_address': 'ईमेल पता',
      'phone_number': 'फोन क्रमांक',
      'my_account': 'माझे खाते',
      'support_more': 'समर्थन आणि बरेच काही',
      'select_language': 'आपनी पसंतीची भाषा निवडा',
      'language_changed': 'भाषा बदलली',
      'language_info': 'भाषा बदल संपूर्ण अ‍ॅपवर लागू होईल',
    },
    'te': {
      'app_name': 'టిఫినిటీ',
      'home': 'హోమ్',
      'my_subscriptions': 'నా సబ్‌స్క్రిప్షన్‌లు',
      'my_orders': 'నా ఆర్డర్‌లు',
      'my_addresses': 'నా చిరునామాలు',
      'wallet_balance': 'వాలెట్ బ్యాలెన్స్',
      'favourites': 'ఇష్టమైనవి',
      'invite_friends': 'స్నేహితులను ఆహ్వానించండి',
      'app_language': 'యాప్ భాష',
      'help_support': 'సహాయం & సపోర్టు',
      'faqs': 'తరచుగా అడిగిన ప్రశ్నలు',
      'logout': 'లాగ్‌అవుట్',
      'login': 'లాగిన్',
      'profile': 'ప్రొఫైల్',
      'contact_details': 'సంपర్క వివరాలు',
      'email_address': 'ఈమెయిల్ చిరునామా',
      'phone_number': 'ఫోన్ సంఖ్య',
      'my_account': 'నా ఖాతా',
      'support_more': 'సపోర్టు & మరిన్ని',
      'select_language': 'మీ ఇష్టపడిన భాషను ఎంచుకోండి',
      'language_changed': 'భాష మార్చబడింది',
      'language_info': 'భాష మార్పులు మొత్తం యాప్‌కు వర్తించబడతాయి',
    },
    'ta': {
      'app_name': 'டிஃபினிட்டி',
      'home': 'முகப்பு',
      'my_subscriptions': 'என் சந்தாக்கள்',
      'my_orders': 'என் ஆர்டர்கள்',
      'my_addresses': 'என் முகவரிகள்',
      'wallet_balance': 'வாலட் நிலுவை',
      'favourites': 'பிடித்தவை',
      'invite_friends': 'நண்பர்களை அழைக்கவும்',
      'app_language': 'பயன்பாட்டு மொழி',
      'help_support': 'உதவி & ஆதரவு',
      'faqs': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      'logout': 'வெளியேறு',
      'login': 'உள்நுழைய',
      'profile': 'சுயவிவரம்',
      'contact_details': 'தொடர்பு விவரங்கள்',
      'email_address': 'மின்னஞ்சல் முகவரி',
      'phone_number': 'தொலைபேசி எண்',
      'my_account': 'என் கணக்கு',
      'support_more': 'ஆதரவு மற்றும் மேலும்',
      'select_language': 'உங்கள் விரும்பிய மொழியைத் தேர்ந்தெடுக்கவும்',
      'language_changed': 'மொழி மாற்றப்பட்டது',
      'language_info': 'மொழி மாற்றம் முழு பயன்பாட்டிற்கும் பொருந்தும்',
    },
    'kn': {
      'app_name': 'ಟಿಫಿನಿಟಿ',
      'home': 'ಮುಖ್ಯಪುಟ',
      'my_subscriptions': 'ನನ್ನ ಸದಸ್ಯತೆಗಳು',
      'my_orders': 'ನನ್ನ ಆದೇಶಗಳು',
      'my_addresses': 'ನನ್ನ ವಿಳಾಸಗಳು',
      'wallet_balance': 'ವಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್',
      'favourites': 'ನೆಚ್ಚಿನವು',
      'invite_friends': 'ಸ್ನೇಹಿತರನ್ನು ಆಮಂತ್ರಿಸಿ',
      'app_language': 'ಅ್ಯಾಪ್ ಭಾಷೆ',
      'help_support': 'ಸಹಾಯ & ಬೆಂಬಲ',
      'faqs': 'ಆಗಾಗ ಕೇಳಿ ಬರುವ ಪ್ರಶ್ನೆಗಳು',
      'logout': 'ಲಾಗ್ಔಟ್',
      'login': 'ಲಾಗಿನ್',
      'profile': 'ಪ್ರೋಫೈಲ್',
      'contact_details': 'ಸಂಪರ್ಕ ವಿವರಗಳು',
      'email_address': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'phone_number': 'ಫೋನ್ ಸಂಖ್ಯೆ',
      'my_account': 'ನನ್ನ ಖಾತೆ',
      'support_more': 'ಬೆಂಬಲ & ಇನ್ನಷ್ಟು',
      'select_language': 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
      'language_changed': 'ಭಾಷೆ ಬದಲಾಯಿಸಲಾಗಿದೆ',
      'language_info': 'ಭಾಷೆಯ ಬದಲಾವಣೆಗಳು ಸಂಪೂರ್ಣ ಅ್ಯಾಪ್‌ನಲ್ಲಿ ಅನ್ವಯ ಆಗುತ್ತವೆ',
    },
    'ml': {
      'app_name': 'ടിഫിനിറ്റി',
      'home': 'ഹോം',
      'my_subscriptions': 'എന്റെ സബ്‌സ്‌ക്രിപ്‌ഷനുകൾ',
      'my_orders': 'എന്റെ ഓർഡർ',
      'my_addresses': 'എന്റെ വിലാസങ്ങൾ',
      'wallet_balance': 'വാലറ്റ് ബാലൻസ്',
      'favourites': 'ഇഷ്ടപ്പെട്ടവ',
      'invite_friends': 'സുഹൃത്തുക്കളെ ക്ഷണിക്കുക',
      'app_language': 'അപ്ലിക്കേഷൻ ഭാഷ',
      'help_support': 'സഹായം & പിന്തുണ',
      'faqs': 'പതിവ് ചോദ്യങ്ങൾ',
      'logout': 'ലോഗൗട്ട്',
      'login': 'ലോഗിൻ',
      'profile': 'പ്രൊഫൈൽ',
      'contact_details': 'ബന്ധപ്പെടാനുള്ള വിശദാംശങ്ങൾ',
      'email_address': 'ഇമെയിൽ വിലാസം',
      'phone_number': 'ഫോൺ നമ്പർ',
      'my_account': 'എന്റെ അക്കൗണ്ട്',
      'support_more': 'പിന്തുണയും കൂടുതലും',
      'select_language': 'നിങ്ങളുടെ ആദ്യ ഭാഷ തിരഞ്ഞെടുക്കുക',
      'language_changed': 'ഭാഷ മാറി',
      'language_info': 'ഭാഷ മാറ്റങ്ങൾ മുഴുവൻ അപ്പിനും ബാധകമായിരിക്കും',
    },
  };

  static String getString(String key, String languageCode) {
    return translations[languageCode]?[key] ?? translations['en']?[key] ?? key;
  }
}
